# Generated by Django 5.2.4 on 2025-07-16 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porject',
            new_name='Project',
        ),
    ]
